import type { Metadata } from 'next';
import {
  //Geist, Geist_Mono,
  Mochiy_Pop_P_One,
} from 'next/font/google';
import './globals.css';
import { Providers } from './providers';

const font = Mochiy_Pop_P_One({
  weight: "400",
  variable: '--font-mochiy-mono',
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} antialiased`}
        style={{overflow: 'hidden'}}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
